테마 생성 기능 구현
Jang-Seong-Bin/Supplies-Wiki pull request #12
Opened 2023-11-12 14:14 UTC by JunyeongJang44

[테마 생성 기능]
- 비즈니스 로직 구현
- VO 구현
- 테스트 코드 성공

[기타]
- 유저 도메인 등, 패키지 이름 변경으로 인한 move 커밋 (임포트 정리)

2023-11-12 15:41 UTC, sshworld commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/request/CreateTheme.kt
> +    val contents: List<Content>,
theme의 content는 list 형태가 아닐 것 같아요! 각 문단으로 이어져 있다 하더라도 하나의 텍스트로 이루어질 것 같습니다!

2023-11-13 00:53 UTC, SheepEatLion commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/request/CreateTheme.kt
> +    val contents: List<Content>,
아 맞다 글 당 하나로 가기로 했었나여

2023-11-13 01:13 UTC, SheepEatLion commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/request/CreateTheme.kt
> +    val contents: List<Content>,
아닌 것 같은데, 생각해보니까 이게 업데이트 생각하다가 얘기 나왔던 거 아닌가???!

2023-11-13 01:14 UTC, SheepEatLion commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/request/CreateTheme.kt
> +    val contents: List<Content>,
content 하나 수정하는 것도 테마에 대한 전체수정으로 받아들여서 버전 업을 해야하니까 그냥 PUT METHOD 로 받을 거 생각하면 그대로 리스트가 맞지 않나요??

2023-11-13 07:06 UTC, sshworld commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/request/CreateTheme.kt
> +    val contents: List<Content>,
맞네요 저도 헷갈렸나봅니다 ㅎㅎ..

2023-11-13 14:54 UTC, ybkim-dev requested changes
고생하셨습니다. 준영님.
리뷰 확인부탁드려요~

2023-11-13 14:54 UTC, ybkim-dev commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/infrastructure/Theme.kt
> +    val category: String,
Category Enum으로 관리하시는게 어떨까요?

2023-11-13 14:54 UTC, ybkim-dev commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/infrastructure/ThemeRepository.kt
> +@Repository
Jpa에서 Repository interface에 애너테이션 필요없었던 걸로 알고 있는데 아닌가요?

2023-11-13 14:54 UTC, ybkim-dev commented on src/test/kotlin/io/jangseongbin/supplieswiki/theme/service/ThemeServiceTest.kt
> +    private val themeService = ThemeService(themeRepository)
Service도 주입받을 수 있지 않나요?

2023-11-17 09:21 UTC, SheepEatLion commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/infrastructure/Theme.kt
> +    val category: String,
아 맞아요 빼둘게요 ㅋㅋㅋ

2023-11-17 09:23 UTC, SheepEatLion commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/infrastructure/ThemeRepository.kt
> +@Repository
맞아요 여기서는 인자가 뭐가 올지 명시해둔 부분을 제거한건데, 인자 이름만으로도 알 수 있어서 그런거에요! themeRepository 라서 레포지토리인걸 아는데 굳이 앞에 레포지토리를 쓸 필요가 없을 것 같아서요. 서비스가 온다고 해도 서비스 이름이 명시 될테니 문제가 없을거라 생각했습니다

2023-11-17 09:29 UTC, SheepEatLion commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/request/CreateTheme.kt
> +    val contents: List<Content>,
네 그렇게 수정했습니당~

2023-11-17 09:30 UTC, merged

2023-11-17 09:31 UTC, ybkim-dev commented on src/main/kotlin/io/jangseongbin/supplieswiki/theme/infrastructure/ThemeRepository.kt
> +@Repository
그래서 `@Repository `를 뗄거라는 말씀이신거죠?